"""GRUB theme generation (Phase-7-completion Section 21).

Branding only - this module never touches GRUB functionality or boot
safety semantics (advanced/recovery options, kernel selection,
diagnostic usefulness are all untouched; nothing here writes
`/etc/default/grub` or regenerates `grub.cfg`). Every color comes from
`branding/tokens/design-tokens.json` via `serein.branding.tokens` -
never a second, hardcoded hex literal (Section 6/36).

No pixmap/image reference is used anywhere in the generated theme -
the master logo asset does not exist yet (`pending_asset_request` in
`serein.branding.manifest`), and GRUB's `gfxmenu` renders a fully
flat-color theme correctly without one. Once the logo exists, a
`desktop-image`/`selected_item_pixmap_style` entry can be added
without restructuring this generator.
"""

from __future__ import annotations

from serein.branding.tokens import load_design_tokens


def render_grub_theme() -> str:
    tokens = load_design_tokens()
    background = tokens.color("background").hex
    text = tokens.color("text").hex
    primary = tokens.color("primary").hex
    focus = tokens.color("focus").hex

    lines = [
        "# Serein GRUB theme (Phase-7-completion Section 21) - branding",
        "# only, generated by serein.branding.grub_theme.render_grub_theme",
        "# from branding/tokens/design-tokens.json. Flat-color only - no",
        "# pixmap/image reference (the master logo asset is pending -",
        "# see serein.branding.manifest). Never edit this file by hand;",
        "# it is deterministic output.",
        "",
        f'desktop-color: "{background}"',
        'title-text: ""',
        "",
        "+ label {",
        '    text = "Serein OS"',
        "    left = 15%",
        '    top = "12%"',
        "    width = 70%",
        f'    color = "{primary}"',
        '    font = "Sans Bold 28"',
        '    align = "left"',
        "}",
        "",
        "+ boot_menu {",
        "    left = 15%",
        '    top = "28%"',
        "    width = 70%",
        "    height = 45%",
        '    item_font = "Sans Regular 16"',
        f'    item_color = "{text}"',
        f'    selected_item_color = "{focus}"',
        "    item_height = 32",
        "    item_padding = 8",
        "    item_spacing = 4",
        "    icon_width = 0",
        "    icon_height = 0",
        "}",
    ]
    return "\n".join(lines) + "\n"
