"""Plymouth boot-splash theme generation (Phase-7-completion Section
22).

**Honesty note (Section 82/29):** Plymouth is not installed anywhere
in this development/CI environment - the generated `.plymouth`
metadata and `.script` content have only ever been reviewed by hand
against Plymouth's own documented theme format and script-language
primitives, never run through a real `plymouth` process. Mirrors this
project's established precedent for
`distribution/systemd/serein-firstboot.service` and
`serein.branding.fastfetch`'s own identical caveat.

No image asset is referenced - the master logo does not exist yet
(`pending_asset_request` in `serein.branding.manifest`). The splash
is entirely color/text driven using Plymouth's own script-language
drawing primitives (no external file needed), so it is genuinely
functional today rather than blocked on the asset request; a future
change can add the real droplet image without restructuring this
module. Minimal animation only (a bounded, subtle opacity pulse on
the wordmark) - never a video or frame sequence (Section 22).
"""

from __future__ import annotations

from serein.branding.tokens import load_design_tokens

THEME_NAME = "serein"


def render_plymouth_metadata() -> str:
    """The `.plymouth` theme descriptor - standard Plymouth ini format."""
    lines = [
        "[Plymouth Theme]",
        f"Name={THEME_NAME.capitalize()}",
        "Description=Serein OS boot splash (Quiet Velocity)",
        "ModuleName=script",
        "",
        "[script]",
        f"ImageDir=/usr/share/plymouth/themes/{THEME_NAME}",
        f"ScriptFile=/usr/share/plymouth/themes/{THEME_NAME}/{THEME_NAME}.script",
    ]
    return "\n".join(lines) + "\n"


def render_plymouth_script() -> str:
    """The Plymouth script - background fill + centered wordmark with a
    subtle, bounded opacity pulse. No external image, no video, no
    frame sequence (Section 22). A script error/failure here must
    never prevent boot - that guarantee comes from Plymouth itself
    (a broken theme script falls back to Plymouth's own built-in
    'details' behavior), not from anything in this file."""
    tokens = load_design_tokens()
    background = tokens.color("background").hex
    text_color = tokens.color("text").hex

    lines = [
        "# Serein Plymouth theme script - generated by",
        "# serein.branding.plymouth_theme.render_plymouth_script from",
        "# branding/tokens/design-tokens.json. Never edit by hand.",
        "",
        f'Window.SetBackgroundTopColor({_hex_to_rgb_expr(background)});',
        f'Window.SetBackgroundBottomColor({_hex_to_rgb_expr(background)});',
        "",
        "wordmark_image = Image.Text(\"SEREIN\", "
        f"{_hex_to_rgb_expr(text_color)}, 1, \"Sans Bold\", 36);",
        "wordmark_sprite = Sprite(wordmark_image);",
        "wordmark_sprite.SetX(Window.GetWidth()  / 2 - wordmark_image.GetWidth()  / 2);",
        "wordmark_sprite.SetY(Window.GetHeight() / 2 - wordmark_image.GetHeight() / 2);",
        "",
        "tagline_image = Image.Text(\"quiet velocity\", "
        f"{_hex_to_rgb_expr(text_color)}, 0.7, \"Sans\", 14);",
        "tagline_sprite = Sprite(tagline_image);",
        "tagline_sprite.SetX(Window.GetWidth()  / 2 - tagline_image.GetWidth()  / 2);",
        "tagline_sprite.SetY(wordmark_sprite.GetY() + wordmark_image.GetHeight() + 12);",
        "",
        "# Subtle, bounded pulse (Section 22 - never a video/frame",
        "# sequence): a slow sine-wave opacity oscillation on the",
        "# wordmark only, between 0.8 and 1.0 - never fully invisible,",
        "# never harsh/flashing.",
        "global.pulse_step = 0;",
        "fun serein_refresh_callback() {",
        "    global.pulse_step++;",
        "    opacity = 0.8 + 0.2 * Math.Sin(global.pulse_step * 0.05);",
        "    wordmark_sprite.SetOpacity(opacity);",
        "}",
        "Plymouth.SetRefreshFunction(serein_refresh_callback);",
        "",
        "# Reduced/no-animation fallback (Section 22): if the boot",
        "# progress signal never arrives (e.g. a very fast boot),",
        "# the static wordmark at full opacity is still a complete,",
        "# correct splash on its own - the pulse is decoration, never",
        "# load-bearing for legibility.",
        "wordmark_sprite.SetOpacity(1);",
    ]
    return "\n".join(lines) + "\n"


def _hex_to_rgb_expr(hex_color: str) -> str:
    """``#RRGGBB`` -> a Plymouth script ``r, g, b`` float-triple
    expression (0.0-1.0 per channel, Plymouth's own documented color
    convention for ``Image.Text``/``Window.SetBackgroundTopColor``)."""
    value = hex_color.lstrip("#")
    r = int(value[0:2], 16) / 255
    g = int(value[2:4], 16) / 255
    b = int(value[4:6], 16) / 255
    return f"{r:.4f}, {g:.4f}, {b:.4f}"
